/**
 *
 * The contents of this file are subject to the terms of the Common Development and
 *  Distribution License (the License). You may not use this file except in compliance with the
 *  License.
 *
 *  You can obtain a copy of the License at https://forgerock.org/cddlv1-0/. See the License for the
 *  specific language governing permission and limitations under the License.
 *
 *  When distributing Covered Software, include this CDDL Header Notice in each file and include
 *  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
 *  Header, with the fields enclosed by brackets [] replaced by your own identifying
 *  information: "Portions copyright [year] [name of copyright owner]".
 *
 *  Copyright 2018 ForgeRock AS.
 */
/*
 * Event Notification API Specification - TPP Endpoints
 * Swagger for Event Notification API Specification - TPP Endpoints
 *
 * OpenAPI spec version: v3.0.0
 * Contact: ServiceDesk@openbanking.org.uk
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package uk.org.openbanking.datamodel.event;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * The resource-update event.
 */
@ApiModel(description = "The resource-update event.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-12-03T11:34:40.772Z")
public class OBEventSubject1 {
  @JsonProperty("subject_type")
  private String subjectType = null;

  @JsonProperty("http://openbanking.org.uk/rid")
  private String httpopenbankingOrgUkrid = null;

  @JsonProperty("http://openbanking.org.uk/rty")
  private String httpopenbankingOrgUkrty = null;

  @JsonProperty("http://openbanking.org.uk/rlk")
  private List<OBEventLink1> httpopenbankingOrgUkrlk = new ArrayList<OBEventLink1>();

  public OBEventSubject1 subjectType(String subjectType) {
    this.subjectType = subjectType;
    return this;
  }

   /**
   * Subject type for the updated resource. 
   * @return subjectType
  **/
  @ApiModelProperty(required = true, value = "Subject type for the updated resource. ")
  public String getSubjectType() {
    return subjectType;
  }

  public void setSubjectType(String subjectType) {
    this.subjectType = subjectType;
  }

  public OBEventSubject1 httpopenbankingOrgUkrid(String httpopenbankingOrgUkrid) {
    this.httpopenbankingOrgUkrid = httpopenbankingOrgUkrid;
    return this;
  }

   /**
   * Resource Id for the updated resource.
   * @return httpopenbankingOrgUkrid
  **/
  @ApiModelProperty(required = true, value = "Resource Id for the updated resource.")
  public String getHttpopenbankingOrgUkrid() {
    return httpopenbankingOrgUkrid;
  }

  public void setHttpopenbankingOrgUkrid(String httpopenbankingOrgUkrid) {
    this.httpopenbankingOrgUkrid = httpopenbankingOrgUkrid;
  }

  public OBEventSubject1 httpopenbankingOrgUkrty(String httpopenbankingOrgUkrty) {
    this.httpopenbankingOrgUkrty = httpopenbankingOrgUkrty;
    return this;
  }

   /**
   * Resource Type for the updated resource.
   * @return httpopenbankingOrgUkrty
  **/
  @ApiModelProperty(required = true, value = "Resource Type for the updated resource.")
  public String getHttpopenbankingOrgUkrty() {
    return httpopenbankingOrgUkrty;
  }

  public void setHttpopenbankingOrgUkrty(String httpopenbankingOrgUkrty) {
    this.httpopenbankingOrgUkrty = httpopenbankingOrgUkrty;
  }

  public OBEventSubject1 httpopenbankingOrgUkrlk(List<OBEventLink1> httpopenbankingOrgUkrlk) {
    this.httpopenbankingOrgUkrlk = httpopenbankingOrgUkrlk;
    return this;
  }

  public OBEventSubject1 addHttpopenbankingOrgUkrlkItem(OBEventLink1 httpopenbankingOrgUkrlkItem) {
    this.httpopenbankingOrgUkrlk.add(httpopenbankingOrgUkrlkItem);
    return this;
  }

   /**
   * Resource links to other available versions of the resource.
   * @return httpopenbankingOrgUkrlk
  **/
  @ApiModelProperty(required = true, value = "Resource links to other available versions of the resource.")
  public List<OBEventLink1> getHttpopenbankingOrgUkrlk() {
    return httpopenbankingOrgUkrlk;
  }

  public void setHttpopenbankingOrgUkrlk(List<OBEventLink1> httpopenbankingOrgUkrlk) {
    this.httpopenbankingOrgUkrlk = httpopenbankingOrgUkrlk;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OBEventSubject1 obEventSubject1 = (OBEventSubject1) o;
    return Objects.equals(this.subjectType, obEventSubject1.subjectType) &&
        Objects.equals(this.httpopenbankingOrgUkrid, obEventSubject1.httpopenbankingOrgUkrid) &&
        Objects.equals(this.httpopenbankingOrgUkrty, obEventSubject1.httpopenbankingOrgUkrty) &&
        Objects.equals(this.httpopenbankingOrgUkrlk, obEventSubject1.httpopenbankingOrgUkrlk);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subjectType, httpopenbankingOrgUkrid, httpopenbankingOrgUkrty, httpopenbankingOrgUkrlk);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OBEventSubject1 {\n");

    sb.append("    subjectType: ").append(toIndentedString(subjectType)).append("\n");
    sb.append("    httpopenbankingOrgUkrid: ").append(toIndentedString(httpopenbankingOrgUkrid)).append("\n");
    sb.append("    httpopenbankingOrgUkrty: ").append(toIndentedString(httpopenbankingOrgUkrty)).append("\n");
    sb.append("    httpopenbankingOrgUkrlk: ").append(toIndentedString(httpopenbankingOrgUkrlk)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

